site_name: 'entrecode API Documentation'
docs_dir: ./doc
theme: readthedocs
extra_css: ['style.css']
pages:
- Basics: 'index.md'
- Account Server: 'account_server.md'
- App Manager: 'app_manager.md'
- Data Manager: 'data_manager.md'
- Account Server Resources:
    - 'Account': 'resources/account.md'
    - 'Auth': 'resources/auth.md'
    - 'Client': 'resources/client.md'
    - 'Invalid Permissions': 'resources/invalid-permissions.md'
    - 'Invites': 'resources/invite.md'
    - 'Group': 'resources/group.md'
    - 'Token': 'resources/token.md'
- App Manager Resources:
    - 'App': 'resources/app.md'
    - 'App Stats': 'resources/app-stats.md'
    - 'Build': 'resources/build.md'
    - 'CodeSource': 'resources/codesource.md'
    - 'DataSource': 'resources/datasource.md'
    - 'Deployment': 'resources/deployment.md'
    - 'Platform': 'resources/platform.md'
    - 'Target': 'resources/target.md'
    - 'Types': 'resources/apptypes.md'
- Data Manager Resources:
    - 'Asset': 'resources/asset.md'
    - 'Client': 'resources/dm-client.md'
    - 'Data Manager': 'resources/datamanager.md'
    - 'Data Manager Account': 'resources/dm-account.md'
    - 'Data Manager Role': 'resources/dm-role.md'
    - 'Data Manager Template': 'resources/dm-template.md'
    - 'Model': 'resources/model.md'
    - 'Tag': 'resources/tag.md'
- SDKs:
    - 'Data Manager Java SDK': 'sdk/datamanager-java.md'
    - 'Data Manager JavaScript SDK': 'sdk/datamanager-js.md'
